[package]
name = "llama-cpp-2"
description = "llama.cpp bindings for Rust"
version = "0.1.52"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/utilityai/llama-cpp-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llama-cpp-sys-2 = { path = "../llama-cpp-sys-2", version = "0.1.52" }
thiserror = { workspace = true }
tracing = { workspace = true }

[features]
cublas = ["llama-cpp-sys-2/cublas"]
metal = ["llama-cpp-sys-2/metal"]
sampler = []

[lints]
workspace = true

[package.metadata.docs.rs]
features = ["sampler"]