name: Llama Cpp Rs Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check:
    name: Run Tests on LLama Cpp Rs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          submodules: recursive
      - name: Install Compile Deps
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get update && sudo apt-get install -y build-essential curl libssl-dev libclang-dev pkg-config cmake git
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Clippy
        run: cargo clippy
      - name: Fmt
        run: cargo fmt
      - name: Test
        run: cargo test --features sampler
  arm64:
    name: Check that it builds on various targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ linux/arm64, linux/amd64 ]
    steps:
      - name: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3
        with:
          platforms: arm64,amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb
      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: test-build.Dockerfile
          target: base-cuda
          platforms: ${{ matrix.target }}
  mac:
    name: Check that it builds on mac
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          submodules: recursive
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --features sampler
  windows:
    name: Check that it builds on windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          submodules: recursive
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --features sampler
      - name: Test
        run: cargo test --features sampler